const {test}=require('node:test'),assert=require('node:assert/strict');const {Game,STEP,portal}=require('../extension/elsewhere-physics.js');
const tick=(g,t)=>{for(let i=0;i<Math.ceil(t/STEP);i++)g.step();};
function playing(){const g=new Game();g.start();g.skipIntro();g.launch();return g;}
function warp(g){g.time=46;for(let i=0;i<4&&!g.warped;i++)g.tryWarp();assert.ok(g.warped);}
test('story holds the ball, emits its melody, and can finish or skip',()=>{const notes=[];const g=new Game(e=>{if(e.type==='introNote')notes.push(e.note);});g.start();const b={...g.ball};tick(g,11);assert.equal(g.state,'intro');assert.deepEqual(g.ball,b);assert.equal(g.time,0);assert.ok(notes.length>=20);tick(g,1.1);assert.equal(g.state,'loaded');assert.ok(g.elapsedTime>=12);g.start();g.skipIntro();assert.equal(g.state,'loaded');assert.equal(g.storyTime,0);});
test('warps require eligible clock visits and enforce a rare cooldown',()=>{const g=playing();assert.equal(g.tryWarp(),false);warp(g);assert.equal(g.warpCount,1);assert.equal(g.tryWarp(),false);g.returnHome();assert.equal(g.tryWarp(),false);assert.equal(g.nextWarpAt,g.time+65);});
test('spin freezes physics; inverted controls map to the visible side',()=>{const g=playing();warp(g);const b={...g.ball};tick(g,1.5);assert.deepEqual(g.ball,b);tick(g,.6);g.input.left=true;g.input.right=false;tick(g,.1);assert.ok(g.flippers[1].angle>Math.PI);assert.ok(g.flippers[0].angle>0);assert.equal(g.input.left,true);assert.equal(g.input.right,false);});
test('warp changes lateral gravity and slows motion, then pays return once',()=>{const g=playing();warp(g);g.time=g.warpStart+5;Object.assign(g.ball,{x:300,y:630,vx:0,vy:0});g.integrateBall(.01);assert.notEqual(g.ball.vx,0);const vy=g.ball.vy;g.time=g.warpStart+12;Object.assign(g.ball,{x:300,y:630,vx:0,vy:0});g.integrateBall(.01);assert.ok(g.ball.vy<vy*.6);assert.equal(g.warpPhase,'slow');const score=g.score;g.time=g.warpUntil-STEP/2;g.step();assert.equal(g.warped,false);assert.equal(g.score-score,3000);g.returnHome();assert.equal(g.score-score,3000);assert.ok(g.saveUntil>g.time);});
test('warp drain rescue keeps the ball, while tilt cancels the warp',()=>{const g=playing();warp(g);g.time=g.warpStart+5;Object.assign(g.ball,{x:295,y:1015,vx:0,vy:500});g.step();assert.equal(g.ballNumber,1);assert.ok(g.ball.vy<0);g.nudge();g.time+=.5;g.nudge();g.time+=.5;g.nudge();assert.equal(g.tilted,true);assert.equal(g.warped,false);assert.equal(g.saveUntil,0);g.start();assert.equal(g.warpCount,0);assert.equal(g.state,'intro');});
test('clock collision can activate a warp, and all launcher charges reach the board',()=>{const g=playing();g.time=46;g.portalVisits=3;Object.assign(g.ball,{x:portal.x,y:portal.y+32,vx:0,vy:-300});g.step();assert.equal(g.warped,true);for(const charge of [0,.25,.5,.75,1]){const game=playing();game.start();game.skipIntro();game.charge=charge;game.launch();let reached=false;for(let i=0;i<240*5;i++){game.step();if(game.ball.x<510)reached=true;assert.ok(Number.isFinite(game.ball.x));}assert.ok(reached);}});
test('extended warped play stays finite and returns to regular controls',()=>{for(let run=0;run<8;run++){const g=playing();warp(g);for(let i=0;i<240*26;i++){g.input.left=Math.sin(i*.015+run)>0;g.input.right=Math.cos(i*.02)>0;g.step();if(g.balls.length){assert.ok(Number.isFinite(g.ball.x)&&Number.isFinite(g.ball.y));assert.ok(g.ball.x>=20&&g.ball.x<=594);}}assert.equal(g.warped,false);assert.equal(g.ballNumber,1);}});
