const {test}=require('node:test'),assert=require('node:assert/strict');
const {Game,Chase,STEP,pocket}=require('../extension/getaway-physics.js');
function drive(g,t){for(let i=0;i<Math.ceil(t/STEP);i++)g.step(STEP);}
function playing(){const g=new Game();g.start();g.launch();return g;}
test('pocket captures a moving ball and freezes the physical table',()=>{const g=playing();Object.assign(g.ball,{x:pocket.x,y:pocket.y+36,vx:10,vy:-100});g.step();assert.equal(g.state,'chase');const ball={...g.ball},time=g.time,angles=g.flippers.map(f=>f.angle);g.input.left=true;drive(g,3);assert.deepEqual(g.ball,ball);assert.equal(g.time,time);assert.deepEqual(g.flippers.map(f=>f.angle),angles);assert.ok(g.chase.player.x<.5);assert.ok(g.elapsedTime>time+2.9);});
test('chase steering is bounded, opposite controls cancel, and damage ends a chase',()=>{const c=new Chase();c.phase='running';for(let i=0;i<240;i++)c.step(STEP,{left:true});assert.ok(c.player.x>=.095&&c.player.x<.2);c.player.vx=0;const x=c.player.x;c.step(STEP,{left:true,right:true});assert.equal(c.player.x,x);for(let i=0;i<3;i++){c.invulnerable=0;c.traffic=[{...c.player,w:.15,h:.13,speed:0,kind:'traffic'}];c.step(STEP,{});}assert.equal(c.health,0);assert.equal(c.phase,'crashed');const time=c.time;for(let i=0;i<550;i++)c.step(STEP,{});assert.equal(c.phase,'finished');assert.equal(c.time,time);});
test('survival bonus pays once, ejects safely, and preserves the ball count',()=>{const g=playing();g.multiplier=3;g.captureBall();g.chase.time=10.4;g.chase.phase='finished';const before=g.score;assert.equal(g.finishChase(),true);assert.equal(g.score-before,7800);assert.equal(g.finishChase(),false);assert.equal(g.state,'playing');assert.equal(g.ballNumber,1);assert.ok(g.ball.vy>0);assert.ok(g.saveUntil>=g.time+3);assert.equal(g.captureBall(),false);});
test('chase escalates with attackers and always returns to play',()=>{const c=new Chase(23);c.time=16;c.wave=12;c.spawn();assert.equal(c.traffic.length,3);assert.ok(c.traffic.some(o=>o.kind==='hunter'));assert.ok(c.traffic.some(o=>o.kind==='pursuer'));const g=playing();g.captureBall();let steps=0;while(g.state==='chase'&&steps++<240*100)g.step();assert.equal(g.state,'playing');assert.ok(g.lastChaseBonus>0);assert.equal(g.ballNumber,1);});
test('restart clears the chase; tilted and unarmed pockets do not capture',()=>{const g=playing();g.tilted=true;assert.equal(g.captureBall(),false);g.tilted=false;g.pocketArmed=false;assert.equal(g.captureBall(),false);g.pocketArmed=true;g.captureBall();drive(g,3);g.start();assert.equal(g.chase,null);assert.equal(g.chaseSeconds,0);assert.equal(g.gear,1);assert.equal(g.score,0);assert.equal(g.pocketArmed,true);assert.equal(g.activateHyperspeed(),false);assert.equal(g.activateMeteorShower(),false);});
test('every launcher strength leaves the shooter lane with finite physics',()=>{for(const charge of [0,.25,.5,.75,1]){const g=new Game();g.start();g.charge=charge;g.launch();let entered=false;for(let i=0;i<240*8;i++){g.step();assert.ok(Number.isFinite(g.ball.x)&&Number.isFinite(g.ball.y));if(g.ball.x<510)entered=true;}assert.ok(entered,'charge '+charge);}});


test('long play reaches the hideout naturally and stays inside the board',()=>{let captures=0;for(let run=0;run<10;run++){const g=new Game(e=>{if(e.type==='chaseStart')captures++;});g.start();g.charge=run/10;g.launch();for(let i=0;i<240*90&&g.state!=='over';i++){if(g.state==='loaded')g.launch();g.input.left=Math.sin(i*.016+run)>0;g.input.right=Math.cos(i*.02+run)>0;g.step();if(g.balls.length){assert.ok(Number.isFinite(g.ball.x)&&Number.isFinite(g.ball.y));assert.ok(g.ball.x>=20&&g.ball.x<=594);}}}assert.ok(captures>0);});
